from tkinter import *

window=Tk()
window.geometry("400x620+100+50")
window.config(background="#455A64")
res=StringVar()
exp=StringVar()
exp.set("")
res.set(0)
opr="+"
def click(n):
    if n=="+" or n=="-" or n=="/" or n=="*":
        if opr=="+":
            exp.set(float(res.get())+float(exp.get()))
    elif n=="=":
        pass
    else:
        exp.set(exp.get()+n)
        print(exp.get())
Label(textvariable=res,height=6,width=20,bg="#455A64",fg="#FFFFFF",).grid(row=0,column=0,columnspan=4)
btn1=Button(text="9",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("9"))
btn2=Button(text="8",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("8"))
btn3=Button(text="7",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("7"))
btn4=Button(text="/",width=6,height=3,bg="#FFEB3B",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("/"))
btn5=Button(text="6",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("6"))
btn6=Button(text="5",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("5"))
btn7=Button(text="4",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("4"))
btn8=Button(text="*",width=6,height=3,bg="#FFEB3B",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("*"))
btn9=Button(text="3",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("3"))
btn10=Button(text="2",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("2"))
btn11=Button(text="1",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("1"))
btn12=Button(text="-",width=6,height=3,bg="#FFEB3B",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("-"))
btn13=Button(text=".",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("."))
btn14=Button(text="0",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("0"))
btn15=Button(text="=",width=6,height=3,bg="#1976D2",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("="))
btn16=Button(text="+",width=6,height=3,bg="#FFEB3B",fg="#FFFFFF",font=("Arial",16,"bold"))
command=lambda:(click("+"))


btn1.grid(row=1,column=0)
btn2.grid(row=1,column=1)
btn3.grid(row=1,column=2)
btn4.grid(row=1,column=3)
btn5.grid(row=2,column=0)
btn6.grid(row=2,column=1)
btn7.grid(row=2,column=2)
btn8.grid(row=2,column=3)
btn9.grid(row=3,column=0)
btn10.grid(row=3,column=1)
btn11.grid(row=3,column=2)
btn12.grid(row=3,column=3)
btn13.grid(row=4,column=0)
btn14.grid(row=4,column=1)
btn15.grid(row=4,column=2)
btn16.grid(row=4,column=3)

window.mainloop()